# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\xy\git\LiGlobal\LiGlobal\tool\downloader\ui\main_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(652, 512)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../icon/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.root_dir_edit = QtWidgets.QLineEdit(self.groupBox_4)
        self.root_dir_edit.setObjectName("root_dir_edit")
        self.horizontalLayout.addWidget(self.root_dir_edit)
        self.root_dir_btn = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.root_dir_btn.setFont(font)
        self.root_dir_btn.setObjectName("root_dir_btn")
        self.horizontalLayout.addWidget(self.root_dir_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.data_type_combox = QtWidgets.QComboBox(self.groupBox_4)
        self.data_type_combox.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.data_type_combox.setFont(font)
        self.data_type_combox.setObjectName("data_type_combox")
        self.data_type_combox.addItem("")
        self.data_type_combox.addItem("")
        self.data_type_combox.addItem("")
        self.horizontalLayout_7.addWidget(self.data_type_combox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.thread_count_edit = QtWidgets.QLineEdit(self.groupBox_4)
        self.thread_count_edit.setObjectName("thread_count_edit")
        self.horizontalLayout_7.addWidget(self.thread_count_edit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.db_radiobtn = QtWidgets.QRadioButton(self.groupBox_4)
        self.db_radiobtn.setObjectName("db_radiobtn")
        self.verticalLayout_2.addWidget(self.db_radiobtn)
        self.widget_access_token = QtWidgets.QWidget(self.groupBox_4)
        self.widget_access_token.setObjectName("widget_access_token")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_access_token)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_11 = QtWidgets.QLabel(self.widget_access_token)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_12.addWidget(self.label_11)
        self.edit_access_token = QtWidgets.QLineEdit(self.widget_access_token)
        self.edit_access_token.setObjectName("edit_access_token")
        self.horizontalLayout_12.addWidget(self.edit_access_token)
        self.verticalLayout_2.addWidget(self.widget_access_token)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.max_lat_edit = QtWidgets.QLineEdit(self.groupBox)
        self.max_lat_edit.setObjectName("max_lat_edit")
        self.horizontalLayout_2.addWidget(self.max_lat_edit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.min_lng_edit = QtWidgets.QLineEdit(self.groupBox)
        self.min_lng_edit.setObjectName("min_lng_edit")
        self.horizontalLayout_3.addWidget(self.min_lng_edit)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.max_lng_edit = QtWidgets.QLineEdit(self.groupBox)
        self.max_lng_edit.setObjectName("max_lng_edit")
        self.horizontalLayout_4.addWidget(self.max_lng_edit)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.min_lat_edit = QtWidgets.QLineEdit(self.groupBox)
        self.min_lat_edit.setObjectName("min_lat_edit")
        self.horizontalLayout_5.addWidget(self.min_lat_edit)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.start_zoom_edit = QtWidgets.QLineEdit(self.groupBox_2)
        self.start_zoom_edit.setObjectName("start_zoom_edit")
        self.horizontalLayout_6.addWidget(self.start_zoom_edit)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_6)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.end_zoom_edit = QtWidgets.QLineEdit(self.groupBox_2)
        self.end_zoom_edit.setObjectName("end_zoom_edit")
        self.horizontalLayout_8.addWidget(self.end_zoom_edit)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.download_btn = QtWidgets.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.download_btn.setFont(font)
        self.download_btn.setObjectName("download_btn")
        self.horizontalLayout_11.addWidget(self.download_btn)
        self.cancel_btn = QtWidgets.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.cancel_btn.setFont(font)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_11.addWidget(self.cancel_btn)
        self.gridLayout_3.addLayout(self.horizontalLayout_11, 0, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_13.addWidget(self.label_9)
        self.progress_bar = QtWidgets.QProgressBar(self.groupBox_3)
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setObjectName("progress_bar")
        self.horizontalLayout_13.addWidget(self.progress_bar)
        self.gridLayout_3.addLayout(self.horizontalLayout_13, 1, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Map Data Downloader"))
        self.label.setText(_translate("Dialog", "Storage directory:"))
        self.root_dir_btn.setText(_translate("Dialog", "Browse"))
        self.label_10.setText(_translate("Dialog", "data type："))
        self.data_type_combox.setItemText(0, _translate("Dialog", "Google image"))
        self.data_type_combox.setItemText(1, _translate("Dialog", "MAP WORLD image"))
        self.data_type_combox.setItemText(2, _translate("Dialog", "Cesium terrain"))
        self.label_8.setText(_translate("Dialog", "thread count："))
        self.db_radiobtn.setText(_translate("Dialog", "write to database"))
        self.label_11.setText(_translate("Dialog", "access_token："))
        self.groupBox.setTitle(_translate("Dialog", "gps"))
        self.label_2.setText(_translate("Dialog", "max latitude:"))
        self.label_3.setText(_translate("Dialog", "min longitude:"))
        self.label_4.setText(_translate("Dialog", "max longitude:"))
        self.label_5.setText(_translate("Dialog", "min latitude:"))
        self.groupBox_2.setTitle(_translate("Dialog", "zoom"))
        self.label_6.setText(_translate("Dialog", "start zoom:"))
        self.label_7.setText(_translate("Dialog", "end zoom:"))
        self.download_btn.setText(_translate("Dialog", "download"))
        self.cancel_btn.setText(_translate("Dialog", "cancel"))
        self.label_9.setText(_translate("Dialog", "progress："))

